Flexible postgres usage

diff --git a/scripts/generate-bosh-lite-manifest b/scripts/generate-bosh-lite-manifest
--- a/scripts/generate-bosh-lite-manifest
+++ b/scripts/generate-bosh-lite-manifest
@@ -14,17 +14,22 @@ MANDATORY ARGUMENTS:
     -c <cf-path>                Path to CF manifest file.
     -i <cloud-config-path>      Path to cloud-config stub file.
     -p <property-path>          Path to property-overrides stub file.
+OPTIONAL ARGUMENTS:
+    -s <postgresql-db-stub-path>     Path to PostgreSQL stub file.
+    -n <instance-count-path>         Path to instance-count-overrides stub file.
 EXAMPLE:
     $0 \\
       -c ../cf-release/bosh-lite/deployments/cf.yml \\
       -i ./example/cloud-config.yml \\
       -p ./example/property-overrides.yml \\
+      -s ./example/postgresql.yml \\
+      -n ./example/instance-count-overrides.yml \\
 EOF
   exit 1
 }
 
 
-while getopts "c:i:p:" opt; do
+while getopts "c:i:p:s:n:" opt; do
   case "$opt" in
     c)
         cf_manifest_file=$OPTARG
@@ -34,6 +39,12 @@ while getopts "c:i:p:" opt; do
         ;;
     p)
         property_overrides=$OPTARG
+        ;;
+    s)
+        postgres_settings=$OPTARG
+        ;;
+    n)
+        instance_counts=$OPTARG
         ;;
     *)  echo "Unknown arguments"
         usage
@@ -73,6 +84,15 @@ else
   fi
 fi
 
+if [[ ! -z "${postgres_settings}" && ! -f "${postgres_settings}" ]]; then
+  >&2 echo "ERROR: PostgreSQL Setting stub '${postgres_settings}' is not a regular file"
+  argument_error=true
+fi
+
+if [[ ! -z "${instance_counts}" && ! -f "${instance_counts}" ]]; then
+  >&2 echo "ERROR: Instance-count-overrides stub '${instance_counts}' is not a regular file"
+  argument_error=true
+fi
 
 if [ ! -z $argument_error ]; then
   echo
@@ -108,6 +128,8 @@ spiff merge \
 ${example}/bosh-lite-manifest-template.yml \
 ${director_uuid} \
 ${property_overrides} \
+${postgres_settings} \
+${instance_counts} \
 ${tmpdir}/config-from-cf-merged.yml  \
 > ${tmpdir}/autoscaler-bosh-lite-manifest.yml
 
